webscarab: 
      :description: ""
      :auth_type: ""
      :username: ""
      :password: ""
      :host: 127.0.0.1
      :domain: ""
      :name: webscarab
      :port: "8008"
      :workstation: ""

:default_proxy: ""  