:cert_file: cert.pem
:key_file: privkey.pem
:dh_key_file: watobo_dh.key
:pass_through: 
  :content_types: 
  - application\/audio
  - application\/video
  - application\/image
  - application\/pdf
  - application\/.*flash
  - image\/
  :content_length: 100000
:certificate_path: certificates
:port: 8081
:server: "127.0.0.1"
  