:sid_patterns: 
- name="(sessid)" value="([0-9a-zA-Z!-]*)"
- (sessid)=([-0-9a-zA-Z_:]*)(;|&)?
- (SESSIONID)=([-0-9a-zA-Z_:\.\(\)]*)(;|&)?
- (PHPSESSID)=([0-9a-zA-Z]*)(;|&)?
- (ASPSESSIONID)\w*=([0-9a-zA-Z]*)(;|&)?
- (MYSAPSSO2)=([0-9a-zA-Z.=%]*)(;|&)?
- (ELEXIRSID)=([0-9a-zA-Z!-]*)(;|&)?
- (SLSID)=([0-9a-zA-Z!-]*)(;|&)?
- (sid)=([0-9a-z]*)(')?
- (saplb_\*)=([-0-9a-zA-Z_:\(\)]*)(;|&)?
- (DomAuthSessId)=([0-9a-zA-Z]*)(;|&)?
- (wgate)\/([\w]{4,}\/[\w=~]*)(;|&|'|")?
- (session)=([-0-9a-zA-Z_:\.]*)(;|&)?
:logout_signatures: 
- ^Location.*login
:smart_scan: true
:custom_error_patterns: []
:excluded_chats: []
:max_parallel_checks: 15
:excluded_parms:
  - __VIEWSTATE
  - __EVENTVALIDATION
:non_unique_parms: []
:smart_scan: true
:www_auth: {}
:scope: {}  
:run_passive_checks: false
:client_certificates: {}
:csrf_patterns:
  - name="(token)" value="([0-9a-zA-Z!-]*)"
  - (token)=([-0-9a-zA-Z_:]*)(;|&)?

  
